// © 2026 Jacquot Digital Solutions. All Rights Reserved.

import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Image,
  Linking,
  TouchableOpacity,
  Platform,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Feather, Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import colors from '../../src/theme/colors';
import { eventInfo } from '../../src/data/mockData';
import { openExternalPage } from '../../src/utils/externalLinks';

const OFFICIAL_IPM_CONTENT = [
  "It is the largest event of its kind in North America.\nWith so much to see and do, plan to spend more than one day!\nHosting the IPM heading into its 107th year is a collaborative effort of the Ontario Plowmen's Association and a Local Committee. It's held in a different community each year, highlighting the many great things the area has to offer and attracting on average 70,000 people from across Ontario, throughout Canada, the United States and beyond.",
  'Activities and entertainment offerings are a little different each year, as the Local Committee puts its own stamp on the IPM, showcasing important local contributions to agriculture and the rural lifestyle. The 2026 event will be held in Bruce County, Ontario from September 22nd to 26th. A team of dedicated local volunteers, alongside the OPA, is hard at work planning and organizing to make this an exceptional IPM.',
  'Tourism industry figures put the economic impact of the IPM at about $25 million annually (not including the long-term benefits this kind of exposure provides to communities). It spurs tourism in the surrounding area for years to come.',
  'More than that, profits generated by the IPM are donated to groups and organizations in the host communities.',
  "It's such an important event, the Provincial Legislature traditionally shuts down so MPPs can attend Opening Day.",
  'An event of this scale would be impossible to put on without hundreds of volunteers and generous support from the business community. We have several sponsors and exhibitors who come with us as we move around the province.',
  'We hope you will visit our website regularly to keep up-to-date and learn how you can participate in IPM 2026!',
] as const;

const OFFICIAL_OPA_CONTENT = {
  whoWeAre: [
    'Plowing Matches have been part of our agricultural history in Ontario for over 150 years. In 1911, separate plowing associations in Ontario came together to form the Ontario Plowmen’s Association (OPA) --- which is a volunteer driven, non-profit organization incorporated under the Agricultural and Horticultural Organizations Act.',
    'The OPA launched the first International Plowing Match & Rural Expo (IPM) in 1913 & this annual event continues to positively influence the province in the areas of agriculture, food, agri-tourism & general tourism throughout rural communities in Ontario.',
  ],
  branchAssociations: [
    'The Ontario Plowmen’s Association has a membership of over 45 local Branch Associations throughout Ontario with approximately 1,000 individual members --- and the Branches hold local Plowing Matches in their communities each year.',
    'Not only do the top plowing competitors from Branch Matches compete at the IPM, individual members also volunteer their time on IPM Local and Provincial Committees and on the OPA Board of Directors.',
  ],
} as const;

export default function AboutScreen() {
  const router = useRouter();

  const openJdsWebsite = () => {
    Linking.openURL('https://jdsstudio.ca');
  };

  const openMaps = () => {
    const { lat, lng } = eventInfo.coordinates;
    const url = Platform.select({
      ios: `maps://app?daddr=${lat},${lng}`,
      android: `geo:${lat},${lng}?q=${lat},${lng}(IPM 2026)`,
      default: `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}`,
    });
    Linking.openURL(url as string);
  };

  const openPastIpmPhotos = () => {
    openExternalPage(router, {
      title: 'Photos of Past IPMs',
      url: 'https://www.plowingmatch.org/ipm2026/visitor-info/photos-of-past-ipms/',
    });
  };

  const openFrequentlyAskedQuestions = () => {
    openExternalPage(router, {
      title: 'Frequently Asked Questions',
      url: 'https://www.plowingmatch.org/ipm2026/visitor-info/faq/',
    });
  };

  const openAccessibilityInformation = () => {
    openExternalPage(router, {
      title: 'Accessibility Information',
      url: 'https://www.plowingmatch.org/ipm2026/visitor-info/accessibility/',
    });
  };

  const openOpaContact = () => {
    openExternalPage(router, {
      title: 'Contact the Ontario Plowmen’s Association',
      url: 'https://www.plowingmatch.org/contact/',
    });
  };

  return (
    <SafeAreaView style={styles.container} edges={['top']}>
      <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
        {/* Event Hero */}
        <View style={styles.heroLogoCard}>
          <Image
            source={require('../../assets/images/gemini4.png')}
            style={styles.heroLogo}
            resizeMode="contain"
          />
        </View>
        <View style={styles.heroIntroduction}>
          <Text style={styles.heroTitle}>International Plowing Match & Rural Expo</Text>
          <View style={styles.heroDetails}>
            <View style={styles.heroDetailRow}>
              <Feather name="map-pin" size={17} color={colors.primary} />
              <Text style={styles.heroDetailText}>Bruce County, Ontario</Text>
            </View>
            <View style={styles.heroDetailRow}>
              <Feather name="calendar" size={17} color={colors.primary} />
              <Text style={styles.heroDetailText}>September 22–26, 2026</Text>
            </View>
          </View>
        </View>

        {/* Directions */}
        <View style={styles.directionsSection}>
          <TouchableOpacity 
            style={styles.directionsButton}
            onPress={openMaps}
            activeOpacity={0.8}
          >
            <Feather name="navigation" size={20} color="#FFFFFF" />
            <Text style={styles.directionsButtonText}>Get Directions</Text>
          </TouchableOpacity>
        </View>

        {/* About the Event */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>About the Event</Text>
          <View style={styles.descriptionCard}>
            {OFFICIAL_IPM_CONTENT.map((paragraph, index) => (
              <Text
                key={paragraph}
                style={[
                  styles.description,
                  index < OFFICIAL_IPM_CONTENT.length - 1 && styles.descriptionParagraph,
                ]}
              >
                {paragraph}
              </Text>
            ))}
          </View>
        </View>

        {/* Visitor Resources */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Visitor Resources</Text>
          <View style={styles.resourceItem}>
            <TouchableOpacity
              style={styles.resourceButton}
              onPress={openPastIpmPhotos}
              activeOpacity={0.8}
              accessibilityRole="button"
              accessibilityLabel="View Photos of Past IPMs"
            >
              <Feather name="image" size={20} color="#FFFFFF" />
              <Text style={styles.resourceButtonText}>View Photos of Past IPMs</Text>
            </TouchableOpacity>
          </View>

          <View style={styles.resourceItem}>
            <TouchableOpacity
              style={styles.resourceButton}
              onPress={openFrequentlyAskedQuestions}
              activeOpacity={0.8}
              accessibilityRole="button"
              accessibilityLabel="Frequently Asked Questions"
            >
              <Feather name="help-circle" size={20} color="#FFFFFF" />
              <Text style={styles.resourceButtonText}>Frequently Asked Questions</Text>
            </TouchableOpacity>
          </View>

          <View style={styles.resourceItem}>
            <TouchableOpacity
              style={styles.resourceButton}
              onPress={openAccessibilityInformation}
              activeOpacity={0.8}
              accessibilityRole="button"
              accessibilityLabel="Accessibility Information"
            >
              <Ionicons name="accessibility" size={21} color="#FFFFFF" />
              <Text style={styles.resourceButtonText}>Accessibility Information</Text>
            </TouchableOpacity>
          </View>
        </View>

        {/* Ontario Plowmen's Association */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>About the Ontario Plowmen&apos;s Association</Text>
          <View style={styles.opaContentCard}>
            <Text style={styles.opaSubsectionTitle}>Who we are</Text>
            {OFFICIAL_OPA_CONTENT.whoWeAre.map((paragraph) => (
              <Text key={paragraph} style={styles.opaParagraph}>{paragraph}</Text>
            ))}

            <Text style={styles.opaSubsectionTitle}>OPA Branch Associations</Text>
            {OFFICIAL_OPA_CONTENT.branchAssociations.map((paragraph) => (
              <Text key={paragraph} style={styles.opaParagraph}>{paragraph}</Text>
            ))}
          </View>

          <View style={styles.opaContactCard}>
            <Image
              source={require('../../assets/images/opa.png')}
              style={styles.opaContactLogo}
              resizeMode="contain"
            />
            <Text style={styles.opaContactName}>Ontario Plowmen&apos;s Association</Text>
            <Text style={styles.opaContactText}>{'188 Nicklin Rd,\nGuelph, Ontario\nN1H 7L5'}</Text>
            <Text style={styles.opaContactText}>519-767-2928 • 800-661-7569</Text>
            <Text style={styles.opaContactEmail}>admin@plowingmatch.org</Text>
            <TouchableOpacity
              style={styles.opaContactButton}
              onPress={openOpaContact}
              activeOpacity={0.8}
              accessibilityRole="button"
              accessibilityLabel="Contact the Ontario Plowmen's Association"
            >
              <Feather name="mail" size={20} color="#FFFFFF" />
              <Text style={styles.opaContactButtonText}>Contact Us</Text>
            </TouchableOpacity>
          </View>
        </View>

        {/* Copyright Footer */}
        <View style={styles.copyrightSection}>
          <TouchableOpacity onPress={openJdsWebsite} activeOpacity={0.75}>
            <Text style={styles.copyrightText}>© 2026 Jacquot Digital Solutions</Text>
            <Text style={styles.copyrightLink}>jdsstudio.ca</Text>
          </TouchableOpacity>
        </View>

        <View style={styles.bottomPadding} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollView: {
    flex: 1,
  },
  heroLogoCard: {
    width: '92%',
    maxWidth: 600,
    aspectRatio: 1,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  heroLogo: {
    width: '100%',
    height: '100%',
  },
  heroIntroduction: {
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  heroTitle: {
    maxWidth: 720,
    color: colors.textPrimary,
    fontSize: 25,
    lineHeight: 31,
    fontWeight: '800',
    textAlign: 'center',
  },
  heroDetails: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 18,
    rowGap: 8,
  },
  heroDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  heroDetailText: {
    color: colors.textSecondary,
    fontSize: 15,
    fontWeight: '700',
  },
  section: {
    paddingHorizontal: 20,
    marginTop: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 16,
  },
  directionsSection: {
    width: '100%',
    maxWidth: 800,
    alignSelf: 'center',
    paddingHorizontal: 20,
    marginTop: 4,
  },
  directionsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: colors.primary,
    paddingVertical: 16,
    borderRadius: 50,
    marginTop: 16,
  },
  directionsButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  descriptionCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 20,
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
  },
  description: {
    fontSize: 15,
    color: colors.textSecondary,
    lineHeight: 24,
  },
  descriptionParagraph: {
    marginBottom: 16,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.surface,
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 32,
    fontWeight: '700',
    color: colors.accent,
  },
  statLabel: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 4,
  },
  opaContentCard: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 20,
  },
  opaSubsectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 10,
  },
  opaParagraph: {
    fontSize: 15,
    color: colors.textSecondary,
    lineHeight: 24,
    marginBottom: 16,
  },
  opaContactCard: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    alignItems: 'center',
    marginTop: 16,
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  opaContactLogo: {
    width: 190,
    height: 94,
  },
  opaContactName: {
    marginTop: 14,
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  opaContactText: {
    marginTop: 12,
    fontSize: 15,
    lineHeight: 22,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  opaContactEmail: {
    marginTop: 12,
    fontSize: 15,
    fontWeight: '600',
    color: colors.primary,
    textAlign: 'center',
  },
  opaContactButton: {
    width: '100%',
    minHeight: 52,
    marginTop: 20,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: colors.primary,
    borderRadius: 50,
  },
  opaContactButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  resourceItem: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    marginTop: 0,
  },
  resourceButton: {
    width: '100%',
    minHeight: 52,
    marginTop: 8,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: colors.primary,
    borderRadius: 50,
  },
  resourceButtonText: {
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  footerBadge: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  footerText: {
    fontSize: 14,
    color: colors.textMuted,
  },
  footerTagline: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.accent,
    marginTop: 4,
    fontStyle: 'italic',
  },
  copyrightSection: {
    marginTop: 24,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  copyrightText: {
    fontSize: 12,
    color: colors.textMuted,
    textAlign: 'center',
  },
  copyrightLink: {
    fontSize: 13,
    color: colors.accent,
    fontWeight: '600',
    marginTop: 4,
    textAlign: 'center',
  },
  bottomPadding: {
    height: 200, // THE SPACER - Critical for scrolling content above floating ad
  },
});
