// © 2026 Jacquot Digital Solutions. All Rights Reserved.

import React, { useCallback, useEffect, useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Image,
  Linking,
  TouchableOpacity,
  Platform,
} from 'react-native';
import { Feather, Ionicons } from '@expo/vector-icons';
import colors from '../../src/theme/colors';
import { attendeePageContent, useAttendeeLayout } from '../../src/theme/attendeePageLayout';
import { eventInfo } from '../../src/data/mockData';
import { openTrackedLink, trackControlledOutbound } from '../../src/analytics/trackedLinks';
import { usePageAnalytics } from '../../src/analytics/usePageAnalytics';
import { AttendeeAttribution } from '../../src/components/AttendeeAttribution';
import {
  readWonderPushRuntimeDiagnostic,
} from '../../src/services/wonderPushRuntimeDiagnostic';
import type { WonderPushRuntimeDiagnostic } from '../../src/services/wonderPushRuntimeDiagnostic';

const OFFICIAL_IPM_CONTENT = [
  "It is the largest event of its kind in North America.\nWith so much to see and do, plan to spend more than one day!\nThe IPM is held in a different community each year, highlighting the many great things the area has to offer and attracting on average 70,000 people from across Ontario, throughout Canada, the United States and beyond.",
  'Activities and entertainment offerings are a little different each year, as the Local Committee puts its own stamp on the IPM, showcasing important local contributions to agriculture and the rural lifestyle. The 2026 event will be held in Bruce County, Ontario from September 22nd to 26th. A team of dedicated local volunteers is hard at work planning and organizing to make this an exceptional IPM.',
  'Tourism industry figures put the economic impact of the IPM at about $25 million annually (not including the long-term benefits this kind of exposure provides to communities). It spurs tourism in the surrounding area for years to come.',
  'More than that, profits generated by the IPM are donated to groups and organizations in the host communities.',
  "It's such an important event, the Provincial Legislature traditionally shuts down so MPPs can attend Opening Day.",
  'An event of this scale would be impossible to put on without hundreds of volunteers and generous support from the business community. We have several sponsors and exhibitors who come with us as we move around the province.',
  'We hope you will visit our website regularly to keep up-to-date and learn how you can participate in IPM 2026!',
] as const;

const EVENT_HISTORY = [
  'Plowing Matches have been part of Ontario’s agricultural history for over 150 years. In 1911, separate plowing associations in Ontario came together to form the Ontario Plowmen’s Association (OPA).',
  'The OPA launched the first International Plowing Match & Rural Expo (IPM) in 1913, beginning the annual event celebrated today.',
] as const;

export default function AboutScreen() {
  usePageAnalytics('about', 'bottom_nav');
  const { frameStyle } = useAttendeeLayout();
  const [wonderPushDiagnostic, setWonderPushDiagnostic] = useState<WonderPushRuntimeDiagnostic | null>(null);
  const [diagnosticRefreshing, setDiagnosticRefreshing] = useState(false);
  const refreshWonderPushDiagnostic = useCallback(async () => {
    setDiagnosticRefreshing(true);
    try {
      setWonderPushDiagnostic(await readWonderPushRuntimeDiagnostic());
    } finally {
      setDiagnosticRefreshing(false);
    }
  }, []);

  useEffect(() => {
    if (Platform.OS === 'web') void refreshWonderPushDiagnostic();
  }, [refreshWonderPushDiagnostic]);
  const openMaps = () => {
    const { lat, lng } = eventInfo.coordinates;
    const url = Platform.select({
      ios: `maps://app?daddr=${lat},${lng}`,
      android: `geo:${lat},${lng}?q=${lat},${lng}(IPM 2026)`,
      default: `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}`,
    });
    trackControlledOutbound('event_directions', 'directions', 'about');
    Linking.openURL(url as string);
  };

  const openPastIpmPhotos = () => {
    void openTrackedLink('past_ipm_photos', 'about');
  };

  const openFrequentlyAskedQuestions = () => {
    void openTrackedLink('faq', 'about');
  };

  const openAccessibilityInformation = () => {
    void openTrackedLink('accessibility', 'about');
  };

  return (
    <View style={[styles.container, attendeePageContent, frameStyle]}>
      <ScrollView style={styles.scrollView} showsVerticalScrollIndicator={false}>
        {/* Event Hero */}
        <View style={styles.heroLogoCard}>
          <Image
            source={require('../../assets/images/gemini4.png')}
            style={styles.heroLogo}
            resizeMode="contain"
          />
        </View>
        <View style={styles.heroIntroduction}>
          <Text style={styles.heroTitle}>International Plowing Match & Rural Expo</Text>
          <View style={styles.heroDetails}>
            <View style={styles.heroDetailRow}>
              <Feather name="map-pin" size={17} color={colors.primary} />
              <Text style={styles.heroDetailText}>Bruce County, Ontario</Text>
            </View>
            <View style={styles.heroDetailRow}>
              <Feather name="calendar" size={17} color={colors.primary} />
              <Text style={styles.heroDetailText}>September 22–26, 2026</Text>
            </View>
          </View>
        </View>

        {/* Directions */}
        <View style={styles.directionsSection}>
          <TouchableOpacity 
            style={styles.directionsButton}
            onPress={openMaps}
            activeOpacity={0.8}
          >
            <Feather name="navigation" size={20} color="#FFFFFF" />
            <Text style={styles.directionsButtonText}>Get Directions</Text>
          </TouchableOpacity>
        </View>

        {/* About the Event */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>About the Event</Text>
          <View style={styles.descriptionCard}>
            {OFFICIAL_IPM_CONTENT.map((paragraph, index) => (
              <Text
                key={paragraph}
                style={[
                  styles.description,
                  index < OFFICIAL_IPM_CONTENT.length - 1 && styles.descriptionParagraph,
                ]}
              >
                {paragraph}
              </Text>
            ))}
          </View>
        </View>

        {/* Visitor Resources */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Visitor Resources</Text>
          <View style={styles.resourceItem}>
            <TouchableOpacity
              style={styles.resourceButton}
              onPress={openPastIpmPhotos}
              activeOpacity={0.8}
              accessibilityRole="button"
              accessibilityLabel="View Photos of Past IPMs"
            >
              <Feather name="image" size={20} color="#FFFFFF" />
              <Text style={styles.resourceButtonText}>View Photos of Past IPMs</Text>
            </TouchableOpacity>
          </View>

          <View style={styles.resourceItem}>
            <TouchableOpacity
              style={styles.resourceButton}
              onPress={openFrequentlyAskedQuestions}
              activeOpacity={0.8}
              accessibilityRole="button"
              accessibilityLabel="Frequently Asked Questions"
            >
              <Feather name="help-circle" size={20} color="#FFFFFF" />
              <Text style={styles.resourceButtonText}>Frequently Asked Questions</Text>
            </TouchableOpacity>
          </View>

          <View style={styles.resourceItem}>
            <TouchableOpacity
              style={styles.resourceButton}
              onPress={openAccessibilityInformation}
              activeOpacity={0.8}
              accessibilityRole="button"
              accessibilityLabel="Accessibility Information"
            >
              <Ionicons name="accessibility" size={21} color="#FFFFFF" />
              <Text style={styles.resourceButtonText}>Accessibility Information</Text>
            </TouchableOpacity>
          </View>
        </View>

        {/* Event History */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Event History</Text>
          <View style={styles.historyCard}>
            {EVENT_HISTORY.map((paragraph) => (
              <Text key={paragraph} style={styles.historyParagraph}>{paragraph}</Text>
            ))}
          </View>
        </View>

        {Platform.OS === 'web' ? (
          <View style={styles.section} testID="wonderpush-runtime-diagnostic">
            <Text style={styles.sectionTitle}>WonderPush runtime session</Text>
            <View style={styles.diagnosticCard}>
              {wonderPushDiagnostic ? (
                <>
                  <Text style={styles.diagnosticLine}>SDK loaded: {wonderPushDiagnostic.sdkLoaded}</Text>
                  <Text style={styles.diagnosticLine}>SDK ready: {wonderPushDiagnostic.sdkReady}</Text>
                  <Text style={styles.diagnosticLine}>Session raw state: {wonderPushDiagnostic.sessionRawState}</Text>
                  <Text style={styles.diagnosticLine}>Session interpreted state: {wonderPushDiagnostic.sessionInterpretedState}</Text>
                  <Text style={styles.diagnosticLine}>Session state observed at: {wonderPushDiagnostic.observedAt}</Text>
                  <Text style={styles.diagnosticLine}>Current installation available: {wonderPushDiagnostic.installationAvailable}</Text>
                  <Text style={styles.diagnosticLine}>WonderPush subscribed: {wonderPushDiagnostic.subscribed}</Text>
                  <Text style={styles.diagnosticLine}>Browser PushSubscription present: {wonderPushDiagnostic.pushSubscriptionPresent}</Text>
                  <Text style={styles.diagnosticLine}>Notification permission: {wonderPushDiagnostic.notificationPermission}</Text>
                  <Text style={styles.diagnosticLine}>Registration workflow state: {wonderPushDiagnostic.registrationWorkflowState}</Text>
                  <Text style={styles.diagnosticLine}>Home classification: {wonderPushDiagnostic.homeClassification}</Text>
                  {wonderPushDiagnostic.transitionHistory.length ? (
                    <View style={styles.transitionHistory}>
                      <Text style={styles.diagnosticHistoryTitle}>Session transitions this app session</Text>
                      {wonderPushDiagnostic.transitionHistory.map((transition, index) => (
                        <Text key={`${transition.observedAt}-${index}`} style={styles.diagnosticLine}>
                          {transition.observedAt} — {transition.interpretedState} ({transition.rawState})
                        </Text>
                      ))}
                    </View>
                  ) : null}
                </>
              ) : <Text style={styles.diagnosticLine}>Diagnostic not read yet.</Text>}
              <TouchableOpacity
                style={styles.diagnosticRefreshButton}
                onPress={() => { void refreshWonderPushDiagnostic(); }}
                disabled={diagnosticRefreshing}
                accessibilityRole="button"
                accessibilityLabel="Refresh WonderPush diagnostic"
              >
                <Text style={styles.diagnosticRefreshText}>
                  {diagnosticRefreshing ? 'Reading…' : 'Refresh WonderPush diagnostic'}
                </Text>
              </TouchableOpacity>
            </View>
          </View>
        ) : null}

        <AttendeeAttribution source="about_attribution" />

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollView: {
    flex: 1,
  },
  heroLogoCard: {
    width: '92%',
    maxWidth: 600,
    aspectRatio: 1,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  heroLogo: {
    width: '100%',
    height: '100%',
  },
  heroIntroduction: {
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  heroTitle: {
    maxWidth: 720,
    color: colors.textPrimary,
    fontSize: 25,
    lineHeight: 31,
    fontWeight: '800',
    textAlign: 'center',
  },
  heroDetails: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'center',
    columnGap: 18,
    rowGap: 8,
  },
  heroDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  heroDetailText: {
    color: colors.textSecondary,
    fontSize: 15,
    fontWeight: '700',
  },
  section: {
    paddingHorizontal: 20,
    marginTop: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 16,
  },
  directionsSection: {
    width: '100%',
    maxWidth: 800,
    alignSelf: 'center',
    paddingHorizontal: 20,
    marginTop: 4,
  },
  directionsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: colors.primary,
    paddingVertical: 16,
    borderRadius: 50,
    marginTop: 16,
  },
  directionsButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  descriptionCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 20,
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
  },
  description: {
    fontSize: 15,
    color: colors.textSecondary,
    lineHeight: 24,
  },
  descriptionParagraph: {
    marginBottom: 16,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.surface,
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
  },
  statNumber: {
    fontSize: 32,
    fontWeight: '700',
    color: colors.accent,
  },
  statLabel: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: 4,
  },
  historyCard: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 20,
  },
  historyParagraph: {
    fontSize: 15,
    color: colors.textSecondary,
    lineHeight: 24,
    marginBottom: 16,
  },
  diagnosticCard: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
  },
  diagnosticLine: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 20,
  },
  diagnosticHistoryTitle: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 4,
  },
  transitionHistory: {
    marginTop: 12,
  },
  diagnosticRefreshButton: {
    minHeight: 44,
    marginTop: 16,
    borderRadius: 22,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  diagnosticRefreshText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  resourceItem: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    marginTop: 0,
  },
  resourceButton: {
    width: '100%',
    minHeight: 52,
    marginTop: 8,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: colors.primary,
    borderRadius: 50,
  },
  resourceButtonText: {
    flexShrink: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  footerBadge: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  footerText: {
    fontSize: 14,
    color: colors.textMuted,
  },
  footerTagline: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.accent,
    marginTop: 4,
    fontStyle: 'italic',
  },
});
