// Browser-only fixtures; all writes/provider calls are blocked.
import assert from 'node:assert/strict';import fs from 'node:fs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base=process.env.IPM_TEST_URL||'http://127.0.0.1:8870',out=process.env.IPM_TEST_OUTPUT||'.artifacts/contextual-help/browser';fs.mkdirSync(out,{recursive:true});
const schedule=JSON.parse(fs.readFileSync(new URL('./fixtures/map-education-schedule.json',import.meta.url)));
const event=schedule.events[0],second={...event,id:'11111111-2222-4333-8444-555555555555',title:'Fixture: second event at the same stage',start_date:'2026-09-24',start_time:'2:30 PM'};const ground={...event,id:'22222222-3333-4444-8555-666666666666',title:'Fixture: Horse Plowing',location_name:'Plowing Fields'};schedule.events.push(second,ground);
const catalog=JSON.parse(fs.readFileSync(new URL('../public/api/vendors.json',import.meta.url))),vendor=catalog.vendors.find(v=>v.name==='Ontario Government');
const keys=['@ipm_schedule_itinerary_onboarding_v1','@ipm_schedule_event_details_tip_seen_v1','@ipm_schedule_find_on_map_tip_seen_v1','@ipm_vendor_find_on_map_tip_seen_v1','@ipm_maps_tour_seen_v1'];
const browser=await chromium.launch();let currentPage;
try {for(const width of [390,768,1440]){
 const c=await browser.newContext({viewport:{width,height:950},serviceWorkers:'block'});
 await c.route('**/*',r=>{const req=r.request(),u=req.url();if(req.method()==='OPTIONS')return r.fulfill({status:204,headers:{'access-control-allow-origin':base,'access-control-allow-credentials':'true','access-control-allow-methods':'GET, OPTIONS','access-control-allow-headers':req.headers()['access-control-request-headers']||'content-type'}});if(req.method()!=='GET'||/wonderpush|webpushr|google-analytics/.test(u))return r.abort();if(u.endsWith('/api/schedule'))return r.fulfill({json:schedule,headers:{'access-control-allow-origin':base,'access-control-allow-credentials':'true'}});if(u.endsWith('/api/vendors'))return r.fulfill({json:{...catalog,vendors:[vendor]}});if(/onrender/.test(u))return r.abort();return r.continue();});
 await c.addInitScript(ks=>{for(const k of ks)localStorage.setItem(k,'true');},keys);
 const p=await c.newPage(),tip=p.getByTestId('map-education-card'),errors=[];currentPage=p;p.on('pageerror',e=>errors.push(e.message));
 await p.goto(base+'/schedule');const sh=p.getByRole('button',{name:'Schedule Help',exact:true});await sh.waitFor();await p.waitForTimeout(800);assert.equal(await p.getByText('Plan your day',{exact:true}).count(),0);await sh.click();await p.getByText('Plan your day',{exact:true}).waitFor();await p.waitForTimeout(450);await p.screenshot({path:`${out}/${width}-schedule-help.png`});await p.getByRole('button',{name:'Got it, close Plan your day introduction'}).click();
 await p.getByText(event.title,{exact:true}).first().scrollIntoViewIfNeeded();await tip.getByText('Tap an event',{exact:true}).waitFor();await p.getByTestId('schedule-education-open-event').click();await p.getByTestId('schedule-find-on-map').scrollIntoViewIfNeeded();await tip.getByText('View event details',{exact:true}).waitFor();await p.getByTestId('schedule-education-open-map').click();
 await p.getByTestId('selected-stage-highlight').waitFor();await p.waitForFunction(title=>document.querySelector('[data-testid=map-selection-title]')?.textContent===title,event.title);assert.doesNotMatch(await p.getByTestId('map-selection-card').innerText(),/10:00|10:15|2:30/);await p.waitForTimeout(300);const closeBox=await p.getByTestId('map-selection-card').getByLabel('Dismiss',{exact:true}).boundingBox(),fitBox=await p.getByLabel('Reset map zoom',{exact:true}).boundingBox();assert(!(closeBox.x<fitBox.x+fitBox.width&&closeBox.x+closeBox.width>fitBox.x&&closeBox.y<fitBox.y+fitBox.height&&closeBox.y+closeBox.height>fitBox.y),'Fit must not cover event close');await p.screenshot({path:`${out}/${width}-event-map.png`});
 await p.goto(base+'/schedule?eventId='+second.id);await p.getByTestId('schedule-find-on-map').scrollIntoViewIfNeeded();await p.getByTestId('schedule-find-on-map').click();await p.waitForFunction(title=>document.querySelector('[data-testid=map-selection-title]')?.textContent===title,second.title);assert(!await p.getByTestId('map-selection-card').innerText().then(t=>t.includes(event.title)));
 await p.goto(base+'/schedule?eventId='+ground.id);await p.getByTestId('schedule-find-on-map').scrollIntoViewIfNeeded();await p.getByTestId('schedule-find-on-map').click();await p.getByTestId('grounds-zone-highlight-horse-plowing').waitFor();await p.waitForFunction(title=>document.querySelector('[data-testid=grounds-info-card] [data-testid=map-selection-title]')?.textContent===title,ground.title);assert.doesNotMatch(await p.getByTestId('grounds-info-card').innerText(),/10:00|10:15/);
 await p.goto(base+'/vendors');const vh=p.getByRole('button',{name:'Vendors Help',exact:true});await vh.waitFor();await vh.click();await tip.getByText('Find this vendor',{exact:true}).waitFor();assert.match(await tip.innerText(),/Tap Find on Map/);assert.equal(await tip.getByRole('button',{name:'Got it',exact:true}).count(),0);await p.screenshot({path:`${out}/${width}-vendor-help.png`});await p.getByTestId('vendor-education-open-map').click();await p.getByTestId('vendor-booth-highlight').waitFor();assert.match(await p.getByTestId('map-selection-title').innerText(),/Ontario Government/);assert.doesNotMatch(await p.getByTestId('map-selection-card').innerText(),/Fixture:|10:00|2:30/);await tip.getByText('Vendor location',{exact:true}).waitFor();await tip.getByRole('button',{name:'Got it',exact:true}).click();
 await p.getByRole('button',{name:'Map Help, replay Maps tour',exact:true}).click();for(let i=0;i<5;i++){await tip.getByText(`${i+1} of 5`,{exact:true}).waitFor();if(i===0)assert.match(await tip.innerText(),/Grounds shows the overall site.*Entrances \/ Parking/s);if(i===2)assert.match(await tip.innerText(),/Tuesday or Wednesday–Saturday/);await tip.getByRole('button',{name:i===4?'Got it':'Next',exact:true}).click();}
 await p.goto(base+'/schedule');await sh.waitFor();assert.equal(await p.getByText('Plan your day',{exact:true}).count(),0);await p.reload();await sh.waitFor();await p.goto(base+'/vendors');await vh.waitFor();await p.waitForTimeout(800);assert.equal(await tip.count(),0);await p.reload();await vh.waitFor();assert.deepEqual(await p.evaluate(ks=>ks.map(k=>localStorage.getItem(k)),keys),keys.map(()=> 'true'));assert.deepEqual(errors,[]);
 console.log(`PASS ${width}: Schedule/Vendors/Maps replay after completion; event title, same-stage switch, vendor identity, no time list, persistence`);await c.close();
}}catch(e){if(currentPage){await currentPage.screenshot({path:`${out}/failure.png`});console.error((await currentPage.locator('body').innerText()).slice(0,2500));}throw e;}finally{await browser.close();}
