const {chromium}=require('/tmp/ipm-browser-tools/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({headless:true,args:['--no-sandbox']});try{
 const p=await b.newPage({viewport:{width:390,height:844},serviceWorkers:'block'});const errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(()=>{navigator.serviceWorker.register=async()=>({waiting:null,installing:null,update:async()=>{},addEventListener(){},removeEventListener(){}});});
 let fakeRelease=false,checks=0;await p.route('**/*',r=>{const u=r.request().url();if(fakeRelease&&u.includes('/app-release.json')){checks++;return r.fulfill({contentType:'application/json',body:JSON.stringify({entry:'/_expo/static/js/web/entry-futuretest.js'})});}return r.request().method()!=='GET'||/wonderpush|webpushr|google-analytics/.test(u)?r.abort():r.continue();});
 const origin=process.env.IPM_PREVIEW_URL || 'http://127.0.0.1:8765';
 await p.goto(origin+'/');await p.getByText('Home',{exact:true}).first().waitFor();console.log('HOME PASS');
 await p.goto(origin+'/vendors');await p.getByText('224 vendors',{exact:true}).waitFor({timeout:60000});
 for(const [q,loc] of [['Valard','EAST-06'],['CAN-AM','WEST-02']]){await p.getByPlaceholder('Search vendors').fill(q);await p.getByText('Location: '+loc,{exact:true}).waitFor();await p.getByText("Exact map location isn't available yet.",{exact:true}).waitFor();assert.equal(await p.getByText('Find on Map',{exact:true}).count(),0);console.log(q+' UNMAPPED PASS');}
 await p.getByPlaceholder('Search vendors').fill('Ontario Government');await p.getByText('Find on Map',{exact:true}).click();await p.getByTestId('vendor-booth-highlight').first().waitFor();await p.getByText('3B-19-24',{exact:true}).first().waitFor();console.log('ONTARIO EXACT MULTIBOOTH PASS');
 await p.goto(origin+'/map?mapType=tented&location=The%20Beyond%20Wireless%20Stage');await p.getByTestId('selected-stage-highlight').waitFor();console.log('MNP FALLBACK PASS');
 await p.goto(origin+'/map');await p.getByLabel('Show camping map',{exact:true}).click();await p.getByTestId('rv-site-search').fill('M27');await p.getByText('RV Site M27',{exact:true}).click();await p.getByTestId('rv-site-title').waitFor();await p.getByText('Row M · Site 27',{exact:true}).waitFor();await p.getByTestId('rv-site-highlight').waitFor();console.log('CAMPING MANUAL M27 PASS');
 await p.goto(origin+'/map');await p.getByLabel('Show grounds map',{exact:true}).first().click();await p.getByTestId('grounds-map-search').fill('Tractor');await p.getByText('Tractor Plowing',{exact:true}).first().click();await p.locator('[data-testid^=grounds-zone-highlight-]').first().waitFor();await p.getByLabel('Dismiss',{exact:true}).click();await p.getByTestId('grounds-fit-reset').click();console.log('GROUNDS TRACTOR / FIT PASS');
 await p.goto(origin+'/about');assert.equal(await p.getByText(/Resume update test:/).count(),0);console.log('NO A/B MARKER');
 await p.goto(origin+'/');await p.getByText('Home',{exact:true}).first().waitFor();await p.waitForTimeout(500);fakeRelease=true;
 await p.evaluate(()=>{let visibility='hidden';Object.defineProperty(document,'visibilityState',{configurable:true,get:()=>visibility});document.dispatchEvent(new Event('visibilitychange'));const now=Date.now;Date.now=()=>now()+600000;visibility='visible';document.dispatchEvent(new Event('visibilitychange'));Date.now=now;});await p.getByText('IPM app update available',{exact:true}).waitFor();assert.equal(checks,1);await p.getByRole('button',{name:'Later',exact:true}).click();console.log('PREVIEW HOME PROMPT / LATER PASS (probe and registration stubbed)');
 assert.deepEqual(errors,[]);console.log('NO BROWSER RUNTIME ERRORS');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
