// Unchanged production artifacts versus candidate. Desktop lab timings only.
const fs=require('node:fs');const {chromium}=require('/tmp/ipm-browser-tools/node_modules/playwright');
const dataCache=new Map();
const ablation=process.env.IPM_PRELOAD_ABLATION==='1';
const variants=ablation?['all','no-grounds','no-tented','no-rv'].map(v=>[v,'http://127.0.0.1:8797']):[['before','http://127.0.0.1:8768'],['after','http://127.0.0.1:8797']];
async function prepare(b,variant){const c=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,serviceWorkers:'block'}),p=await c.newPage(),cd=await c.newCDPSession(p);await cd.send('Network.enable');await cd.send('Fetch.enable',{patterns:[{urlPattern:'*'}]});
 cd.on('Fetch.requestPaused',async e=>{try{const q=e.request,u=new URL(q.url);if(q.method!=='GET'||/wonderpush|webpushr/.test(q.url))return await cd.send('Fetch.failRequest',{requestId:e.requestId,errorReason:'BlockedByClient'});if(u.hostname==='ipm-backend-eoiw.onrender.com'){if(!dataCache.has(q.url))dataCache.set(q.url,fetch(q.url).then(async r=>({status:r.status,body:Buffer.from(await r.arrayBuffer()).toString('base64')})));const r=await dataCache.get(q.url);return await cd.send('Fetch.fulfillRequest',{requestId:e.requestId,responseCode:r.status,responseHeaders:[{name:'Content-Type',value:'application/json'},{name:'Access-Control-Allow-Origin',value:'*'}],body:r.body})}await cd.send('Fetch.continueRequest',{requestId:e.requestId})}catch{}});
 await p.addInitScript(()=>{window.artworkDecodes=[];const orig=HTMLImageElement.prototype.decode;HTMLImageElement.prototype.decode=function(){const row={url:this.src,start:performance.now()};window.artworkDecodes.push(row);return orig.call(this).then(v=>{row.end=performance.now();return v},e=>{row.end=performance.now();throw e})}});if(ablation&&variant.startsWith('no-'))await p.addInitScript(omit=>{
 // Diagnostic-only ablation: suppress just the background Image, leaving the
 // actual production renderer and its requests unchanged.
 const file={grounds:'grounds-site-map',tented:'tented-city-map-app-ready',rv:'rv-park-detail-map'}[omit];
 const descriptor=Object.getOwnPropertyDescriptor(HTMLImageElement.prototype,'src');
 Object.defineProperty(HTMLImageElement.prototype,'src',{...descriptor,set(value){if(this.fetchPriority==='low'&&String(value).includes(file)){setTimeout(()=>this.onerror?.(new Event('error')),0);return;}descriptor.set.call(this,value);}});
},variant.slice(3));return{c,p};}
(async()=>{const b=await chromium.launch({headless:true,args:['--no-sandbox']});const rows=[];try{
 for(let run=0;run<4;run++)for(const [variant,origin]of variants){const {c,p}=await prepare(b,variant);await p.goto(origin+'/',{waitUntil:'domcontentloaded'});await p.getByText('Home',{exact:true}).first().waitFor();await p.getByText('Quick Actions',{exact:true}).waitFor();const home=await p.evaluate(()=>performance.now());
 await p.waitForTimeout(11000);const homeState=await p.evaluate(()=>({marks:performance.getEntriesByType('mark').filter(e=>e.name.startsWith('ipm-map-preload')).map(e=>({name:e.name,t:e.startTime})),dividers:document.querySelectorAll('[data-testid="booth-divider"]').length,decodes:window.artworkDecodes.filter(e=>/grounds-site-map|tented-city-map-app-ready|rv-park-detail-map/.test(e.url))}));
 const opens=[];
 for(const mode of ['grounds','tented','rv','grounds','tented','rv']){const start=await p.evaluate(()=>performance.now());if(!opens.length)await p.getByText('Map',{exact:true}).click();else await p.getByTestId('map-mode-'+mode).click();await p.waitForFunction(({mode,candidate})=>{const file={grounds:'grounds-site-map',tented:'tented-city-map-app-ready',rv:'rv-park-detail-map'}[mode],im=document.querySelector(`img[src*="${file}"]`);return im?.complete&&im.naturalWidth>0&&(!candidate||!document.querySelector(`[data-testid="map-artwork-${mode}-loading"]`))},{mode,candidate:variant!=='before'});const end=await p.evaluate(()=>performance.now());opens.push({mode,ms:end-start,dividers:await p.getByTestId('booth-divider').count()})}
 const resources=await p.evaluate(()=>performance.getEntriesByType('resource').filter(r=>/grounds-site-map|tented-city-map-app-ready|rv-park-detail-map/.test(r.name)).map(r=>({url:r.name,start:r.startTime,end:r.responseEnd,bytes:r.transferSize,body:r.encodedBodySize})));
 const row={run,variant,home,homeState,opens,resources};rows.push(row);console.log(JSON.stringify(row));fs.writeFileSync('../diagnostics/map-startup/'+(ablation?'ablation':'measurements')+'.json',JSON.stringify(rows,null,2));await c.close();}
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
