// Use the generated shell with the existing provider URL replaced by a local no-op by the test server.
const assert=require('node:assert/strict');const{chromium}=require(process.env.IPM_PLAYWRIGHT_MODULE||'/tmp/ipm-browser-tools/node_modules/playwright');
const origin=process.env.IPM_PREVIEW_URL||'http://127.0.0.1:8870';assert.ok(origin.startsWith('http://127.0.0.1:'));
(async()=>{const b=await chromium.launch({args:['--no-sandbox']});try{
 const c=await b.newContext({viewport:{width:393,height:852}});await c.route('**/*',r=>r.request().method()!=='GET'||(!r.request().url().startsWith(origin)&&/wonderpush|webpushr|google-analytics|onrender/.test(r.request().url()))?r.abort():r.continue());const p=await c.newPage();await p.goto(origin+'/map');await p.getByTestId('map-education-card').getByRole('button',{name:'Skip tutorial'}).click();
 await p.evaluate(async()=>{await navigator.serviceWorker.register('/webpushr-sw.js');await navigator.serviceWorker.ready;});await p.waitForFunction(async()=>!!(await caches.match('/index.html')));await p.waitForFunction(async()=>{const d=await(await fetch('/app-release.json')).json();return !!await caches.match(d.entry)});
 await c.setOffline(true);await p.reload();await p.getByRole('button',{name:'Map Help, replay Maps tour'}).waitFor();await p.waitForTimeout(800);assert.equal(await p.getByTestId('map-education-card').count(),0);await p.getByRole('button',{name:'Map Help, replay Maps tour'}).click();const card=p.getByTestId('map-education-card');for(const [i,title] of ['Find parking','Find a place','Follow the parade','Move around the map','Find your campsite'].entries()){await card.getByText(title,{exact:true}).waitFor();await card.getByText(`${i+1} of 5`,{exact:true}).waitFor();await card.getByRole('button',{name:i===4?'Got it':'Next',exact:true}).click();}await card.waitFor({state:'hidden'});await p.reload();await p.getByRole('button',{name:'Map Help, replay Maps tour'}).waitFor();await p.waitForTimeout(800);assert.equal(await card.count(),0);
 await p.getByTestId('map-mode-rv').click();await p.getByTestId('rv-site-search').fill('M27');await p.getByText('RV Site M27',{exact:true}).click();await p.getByTestId('rv-site-highlight').waitFor();assert.equal(await p.evaluate(()=>localStorage.getItem('@ipm_maps_tour_seen_v1')),'true');console.log('PASS offline preflight: generated shell cached, offline reload, seen state retained, Help works offline, Camping/M27 works offline; no provider calls');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
